In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [12]:
df = yf.download("QQQ",period="5y",interval="1d").reset_index()

[*********************100%***********************]  1 of 1 completed

C:\Users\DELL\anaconda3\lib\site-packages\yfinance\utils.py:631: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

In [13]:
df['rate']=((df['Close']/df['Open'])-1)*100

In [14]:
df['body-wick'] = np.abs(df['Close']-df['Open'])/np.abs(df['High']-df['Low'])

In [15]:
df['upshadow']=np.where((df['Close']/df['Open'])-1>0,
                       np.abs(df['High']-df['Close'])/np.abs(df['High']-df['Low']),
                       np.abs(df['High']-df['Open'])/np.abs(df['High']-df['Low']))

In [16]:
df['downshadow']=np.where((df['Close']/df['Open'])-1>0,
                       np.abs(df['Low']-df['Open'])/np.abs(df['Low']-df['High']),
                       np.abs(df['Low']-df['Close'])/np.abs(df['Low']-df['High']))

In [17]:
df['bullpwr']=df['body-wick']+df['downshadow']
df['bearpwr']=df['body-wick']+df['upshadow']

Bull: 
-Min Upshadow
-Max Downshadow

Bear:
-Max Upshadow
-Min Downshadow

In [18]:
df[df['Date']=='2023-03-06'][['Date','body-wick','upshadow','downshadow']]

                         Date  body-wick  upshadow  downshadow
901 2023-03-06 00:00:00-05:00   0.220099  0.732058    0.047843

In [19]:
df.tail(30)[['Date','body-wick','upshadow','downshadow']]

                          Date  body-wick  upshadow  downshadow
1228 2024-06-24 00:00:00-04:00   0.690673  0.286416    0.022911
1229 2024-06-25 00:00:00-04:00   0.725877  0.065787    0.208336
1230 2024-06-26 00:00:00-04:00   0.652330  0.197139    0.150531
1231 2024-06-27 00:00:00-04:00   0.392101  0.392109    0.215790
1232 2024-06-28 00:00:00-04:00   0.377576  0.548055    0.074370
1233 2024-07-01 00:00:00-04:00   0.301767  0.091489    0.606743
1234 2024-07-02 00:00:00-04:00   0.971893  0.008875    0.019231
1235 2024-07-03 00:00:00-04:00   0.973736  0.026264    0.000000
1236 2024-07-05 00:00:00-04:00   0.852292  0.087825    0.059884
1237 2024-07-08 00:00:00-04:00   0.337500  0.233333    0.429167
1238 2024-07-09 00:00:00-04:00   0.292554  0.300532    0.406914
1239 2024-07-10 00:00:00-04:00   0.633531  0.109162    0.257307
1240 2024-07-11 00:00:00-04:00   0.887651  0.016732    0.095616
1241 2024-07-12 00:00:00-04:00   0.304750  0.633245    0.062006
1242 2024-07-15 00:00:00-04:00   0.066473  0.635840    0.297687
1243 2024-07-16 00:00:00-04:00   0.241965  0.155011    0.603024
1244 2024-07-17 00:00:00-04:00   0.916906  0.073238    0.009856
1245 2024-07-18 00:00:00-04:00   0.639831  0.019067    0.341102
1246 2024-07-19 00:00:00-04:00   0.504517  0.327743    0.167740
1247 2024-07-22 00:00:00-04:00   0.205674  0.182623    0.611703
1248 2024-07-23 00:00:00-04:00   0.184152  0.703964    0.111884
1249 2024-07-24 00:00:00-04:00   0.893836  0.031678    0.074486
1250 2024-07-25 00:00:00-04:00   0.442731  0.342811    0.214459
1251 2024-07-26 00:00:00-04:00   0.051949  0.480518    0.467533
1252 2024-07-29 00:00:00-04:00   0.287758  0.349763    0.362479
1253 2024-07-30 00:00:00-04:00   0.670427  0.057211    0.272361
1254 2024-07-31 00:00:00-04:00   0.501569  0.269592    0.228839
1255 2024-08-01 00:00:00-04:00   0.618294  0.193663    0.188043
1256 2024-08-02 00:00:00-04:00   0.235166  0.294504    0.470329
1257 2024-08-05 00:00:00-04:00   0.565818  0.367304    0.066878