In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('datasimple.csv')

In [3]:
df['time']=df['time'].apply(lambda x:x.split('+')[0])
df['time']=pd.to_datetime(df['time'])

In [4]:
df.head()

,time,open,high,low,close,KAMA,Volume,Volume MA
0,2020-11-11 02:00:00,450.34,476.25,449.28,463.09,409.605256,1.205783e+06,891616.690705
1,2020-11-12 02:00:00,463.09,470.00,451.20,462.39,411.539989,9.907766e+05,904763.906041
2,2020-11-13 02:00:00,462.48,478.01,457.12,476.43,415.100806,9.766651e+05,932635.317364
3,2020-11-14 02:00:00,476.42,477.47,452.00,460.89,416.605915,7.352528e+05,948618.607829
4,2020-11-15 02:00:00,460.90,462.89,440.19,448.08,417.443094,6.652176e+05,937122.352532

In [5]:
from ta import add_all_ta_features

In [6]:
df=add_all_ta_features(df,open='open',high='high',low='low',close='close',volume='Volume')

/Users/mert/opt/anaconda3/lib/python3.9/site-packages/ta/trend.py:780: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
/Users/mert/opt/anaconda3/lib/python3.9/site-packages/ta/trend.py:785: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

In [7]:
df.columns

Index(['time', 'open', 'high', 'low', 'close', 'KAMA', 'Volume', 'Volume MA',
       'volume_adi', 'volume_obv', 'volume_cmf', 'volume_fi', 'volume_em',
       'volume_sma_em', 'volume_vpt', 'volume_vwap', 'volume_mfi',
       'volume_nvi', 'volatility_bbm', 'volatility_bbh', 'volatility_bbl',
       'volatility_bbw', 'volatility_bbp', 'volatility_bbhi',
       'volatility_bbli', 'volatility_kcc', 'volatility_kch', 'volatility_kcl',
       'volatility_kcw', 'volatility_kcp', 'volatility_kchi',
       'volatility_kcli', 'volatility_dcl', 'volatility_dch', 'volatility_dcm',
       'volatility_dcw', 'volatility_dcp', 'volatility_atr', 'volatility_ui',
       'trend_macd', 'trend_macd_signal', 'trend_macd_diff', 'trend_sma_fast',
       'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow',
       'trend_vortex_ind_pos', 'trend_vortex_ind_neg', 'trend_vortex_ind_diff',
       'trend_trix', 'trend_mass_index', 'trend_dpo', 'trend_kst',
       'trend_kst_sig', 'trend_kst_diff', 'trend_ichimoku_conv',
       'trend_ichimoku_base', 'trend_ichimoku_a', 'trend_ichimoku_b',
       'trend_stc', 'trend_adx', 'trend_adx_pos', 'trend_adx_neg', 'trend_cci',
       'trend_visual_ichimoku_a', 'trend_visual_ichimoku_b', 'trend_aroon_up',
       'trend_aroon_down', 'trend_aroon_ind', 'trend_psar_up',
       'trend_psar_down', 'trend_psar_up_indicator',
       'trend_psar_down_indicator', 'momentum_rsi', 'momentum_stoch_rsi',
       'momentum_stoch_rsi_k', 'momentum_stoch_rsi_d', 'momentum_tsi',
       'momentum_uo', 'momentum_stoch', 'momentum_stoch_signal', 'momentum_wr',
       'momentum_ao', 'momentum_roc', 'momentum_ppo', 'momentum_ppo_signal',
       'momentum_ppo_hist', 'momentum_pvo', 'momentum_pvo_signal',
       'momentum_pvo_hist', 'momentum_kama', 'others_dr', 'others_dlr',
       'others_cr'],
      dtype='object')

In [8]:
df

,time,open,high,low,close,KAMA,Volume,Volume MA,volume_adi,volume_obv,...,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_pvo,momentum_pvo_signal,momentum_pvo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,2020-11-11 02:00:00,450.34,476.25,449.28,463.09,409.605256,1.205783e+06,891616.690705,2.906039e+04,1.205783e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-80.856621,NaN,0.000000
1,2020-11-12 02:00:00,463.09,470.00,451.20,462.39,411.539989,9.907766e+05,904763.906041,2.177296e+05,2.150062e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.151159,-0.151273,-0.151159
2,2020-11-13 02:00:00,462.48,478.01,457.12,476.43,415.100806,9.766651e+05,932635.317364,1.046656e+06,1.191671e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.036398,2.991212,2.880650
3,2020-11-14 02:00:00,476.42,477.47,452.00,460.89,416.605915,7.352528e+05,948618.607829,8.246656e+05,4.564185e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.261759,-3.316140,-0.475070
4,2020-11-15 02:00:00,460.90,462.89,440.19,448.08,417.443094,6.652176e+05,937122.352532,6.218768e+05,-2.087990e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.779405,-2.818761,-3.241271
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,2021-12-03 02:00:00,4511.35,4654.88,4032.50,4215.73,4329.238337,6.779713e+05,478905.493415,6.981374e+07,4.468095e+07,...,0.574393,0.524635,0.049758,7.174130,3.817868,3.356263,4295.152472,-6.549906,-6.774264,810.347881
388,2021-12-04 02:00:00,4215.01,4238.59,3503.68,4117.25,4324.471512,1.111471e+06,522213.576165,7.055818e+07,4.356947e+07,...,0.054037,0.430515,-0.376478,15.211802,6.096655,9.115147,4292.829800,-2.336013,-2.363730,789.082036
389,2021-12-05 02:00:00,4117.25,4248.19,4031.39,4196.44,4322.203504,5.363254e+05,530258.765225,7.083847e+07,4.410580e+07,...,-0.210877,0.302237,-0.513114,13.047622,7.486848,5.560774,4289.591469,1.923371,1.905108,806.182384
390,2021-12-06 02:00:00,4196.44,4376.15,3921.00,4347.59,4322.448276,7.261050e+05,529771.161320,7.147345e+07,4.483191e+07,...,-0.137310,0.214327,-0.351637,13.722138,8.733906,4.988232,4291.981099,3.601863,3.538512,838.821827
391,2021-12-07 02:00:00,4347.57,4425.00,4257.42,4284.52,4322.220051,3.883015e+05,525543.625585,7.121073e+07,4.444360e+07,...,-0.194587,0.132544,-0.327132,9.577930,8.902711,0.675219,4291.814428,-1.450689,-1.461314,825.202444